export GOOGLE_CLOUD_PROJECT=YOUR_PROJECT_ID
export GOOGLE_CLOUD_LOCATION=YOUR_REGION
export APIGEE_TYPE=EVALUATION

# Optional
export APIGEE_VPC_NAME=
export APIGEE_SUBNET_NAME=
export APIGEE_DRZ_LOCATION=
